apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app1
  labels: 
    purpose: ALB
    component: app1
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      purpose: ALB
      component: app1
      project: roboshop
  template:
    metadata:
      labels:
        purpose: ALB
        component: app1
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
---

apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    purpose: ALB
    component: app1
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    alb.ingress.kubernetes.io/listen-ports: 443
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:535239896506:certificate/31e5a37b-7158-497e-bea0-80aa44adbb61
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: roboshop

spec:
  ingressClassName: alb
  rules:
  - host: "app1.someshwar.fun"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80
